language: python
python:
  - 2.6
  - 2.7
install:
  - ./.travis_setup
env:
  - DJANGO_VERSION=1.3.2 DJANGO_CMS_VERSION=2.2
  - DJANGO_VERSION=1.3.2 DJANGO_CMS_VERSION=2.3
  - DJANGO_VERSION=1.4.1 DJANGO_CMS_VERSION=2.2
  - DJANGO_VERSION=1.4.1 DJANGO_CMS_VERSION=2.3
script: python setup.py test
