language: python
python:
  - 2.6
  - 2.7
install:
  - ./.travis_setup
env:
  - DJANGO="django>=1.3,<1.4" DJANGO_CMS="django-cms>=2.2,<2.3"
  - DJANGO="django>=1.3,<1.4" DJANGO_CMS="django-cms>=2.3,<2.4"
  - DJANGO="django>=1.4,<1.5" DJANGO_CMS="django-cms>=2.2,<2.3"
  - DJANGO="django>=1.4,<1.5" DJANGO_CMS="django-cms>=2.3,<2.4"
script: python setup.py test
